version: '3.8'

services:
  gpt-backend:
    build: 
      context: gpt3
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  gpt-frontend:
    build: 
      context: chatgpt-clone
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - gpt-backend